# Data transformation

We can use the code below to download the NYC Crime data

crime_file = "nypd.csv"
crime_url = "https://data.cityofnewyork.us/api/views/qgea-i56i/rows.csv?accessType=DOWNLOAD"
download.file(crime_url,crime_file)
NYPD_Complaint_Data_Historic <-read.csv(crime_file,stringsAsFactors = FALSE)

However, since it is too large (2G), I will just read the data from my own computer

```{r}
library(readr)
NYPD_Complaint_Data_Historic <- read_csv("~/Downloads/NYPD_Complaint_Data_Historic.csv")
```
```{r}
library(lubridate)
# formate the date in (month/day/Year)
NYPD_Complaint_Data_Historic$CMPLNT_FR_DT <- as.Date(NYPD_Complaint_Data_Historic$CMPLNT_FR_DT,'%m/%d/%Y')
# subset the data in year 2020
d1 <- NYPD_Complaint_Data_Historic[is.na(NYPD_Complaint_Data_Historic$CMPLNT_FR_DT) == FALSE  & year(NYPD_Complaint_Data_Historic$CMPLNT_FR_DT) == 2020 ,]
# pick the column we need
d2 <- d1[,c("CMPLNT_NUM","CMPLNT_FR_DT","CMPLNT_FR_TM","OFNS_DESC","CRM_ATPT_CPTD_CD","LAW_CAT_CD","BORO_NM","PREM_TYP_DESC","Latitude","Longitude","VIC_RACE","VIC_SEX")]
```

```{r}
# keep the first eleven OFNS_DESC and change all the other into "Others
gg <- (d2$OFNS_DESC != 'PETIT LARCENY'&
    d2$OFNS_DESC != 'HARRASSMENT 2'&
    d2$OFNS_DESC != 'ASSAULT 3 & RELATED OFFENSES' &
    d2$OFNS_DESC !='CRIMINAL MISCHIEF & RELATED OF' &
    d2$OFNS_DESC != 'GRAND LARCENY'&
    d2$OFNS_DESC != 'FELONY ASSAULT'&
    d2$OFNS_DESC != 'OFF. AGNST PUB ORD SENSBLTY &'&
    d2$OFNS_DESC != 'MISCELLANEOUS PENAL LAW'&
    d2$OFNS_DESC != 'DANGEROUS DRUGS' &
    d2$OFNS_DESC != 'ROBBERY'&
    d2$OFNS_DESC != 'BURGLARY')
d2$OFNS_DESC[gg] = "Others"

# keep the first fourteen PREN_TYP_DESC 
kk <- (d2$PREM_TYP_DESC != 'STREET'&
    d2$PREM_TYP_DESC != 'CHAIN STORE'&
    d2$PREM_TYP_DESC != 'RESIDENCE-HOUSE' &
    d2$PREM_TYP_DESC != 'RESIDENCE - APT. HOUSE' &
    d2$PREM_TYP_DESC !='RESIDENCE - PUBLIC HOUSING' &
    d2$PREM_TYP_DESC != 'COMMERCIAL BUILDING'&
    d2$PREM_TYP_DESC != 'DRUG STORE'&
    d2$PREM_TYP_DESC != 'GROCERY/BODEGA'&
    d2$PREM_TYP_DESC != 'TRANSIT - NYC SUBWAY'&
    d2$PREM_TYP_DESC != 'DEPARTMENT STORE' &
    d2$PREM_TYP_DESC != 'RESTAURANT/DINER'&
    d2$PREM_TYP_DESC != 'PARK/PLAYGROUND' &
    d2$PREM_TYP_DESC != 'CLOTHING/BOUTIQUE' &
    d2$PREM_TYP_DESC != 'HOMELESS SHELTER' 
    )
d2$PREM_TYP_DESC[kk] = "Others"
```

```{r}
# change to factor
d2$CRM_ATPT_CPTD_CD <- as.factor(d2$CRM_ATPT_CPTD_CD)
d2$LAW_CAT_CD <- as.factor((d2$LAW_CAT_CD))
d2$BORO_NM <- as.factor(d2$BORO_NM)
d2$VIC_RACE <- as.factor(d2$VIC_RACE)
d2$VIC_SEX <- as.factor(d2$VIC_SEX)
d2$PREM_TYP_DESC<- as.factor(d2$PREM_TYP_DESC)
d2$OFNS_DESC <- as.factor(d2$OFNS_DESC)
```

```{r}
library(tidyr)
library(dplyr)
# get a new column of month
d2 <- d2 %>%
  mutate(month = month(CMPLNT_FR_DT))
d2$month <- as.factor(d2$month)

# change time into time range in 1 hour
time_range<- data.frame(id=c(0:24),
                        range= c("00-01","01-02","02-03","03-04","04-05","05-06","06-07","07-08",
                                  "08-09","09-10","10-11","11-12","12-13","13-14","14-15","15-16",
                                  "16-17","17-18","18-19","19-20","20-21","21-22","22-23","23-24","00-01"))

d3 <- d2 %>%
   mutate(Date = CMPLNT_FR_DT) %>%
   mutate(DayofWeek = wday(Date,label = TRUE,abbr = FALSE),
         Day=wday(Date), 
         Time = hour(hms(CMPLNT_FR_TM))) %>%
  mutate(TimeRange = time_range$range[match(.$Time, time_range$id)])
d3$TimeRange <- as.factor(d3$TimeRange)
```

```{r}
d4 <- d3 %>%
  select(CMPLNT_NUM,Date,month,DayofWeek,Day,TimeRange,BORO_NM,PREM_TYP_DESC,Latitude,Longitude,OFNS_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,VIC_RACE,VIC_SEX)
names(d4) <- c("CaseID","Date","Month","Weekday","WeekdayN","TimeRange","County","Location","Latitude","Longitude","Offense","Status","level","VIC_Race","VIC_Sex")
summary(d4)
```

```{r}
write.csv(x = d4,file = "Crime.csv")
```



